(* ::Package:: *)

(* ::Input:: *)
(*TestReport[ (*string handling*)*)
(*	{VerificationTest[*)
(*		productStrings["Ba2MgGe2O7 <- BaCO3 + MgO + GeO2"],*)
(*{"BaCO3 + MgO + GeO2"}],*)
(**)
(*VerificationTest[*)
(*productStrings["YFeO3 <- Y2O3 + Fe2O3\n\nYFeO3 <- Y(NO3)3 + Fe(NO3)3\n\nYFeO3 <- Y2O3 + Fe3O4\n\nYFeO3 <- Y(NO3)3 + Fe2O3\n\nYFeO3 <- Y2O3 + FeO"],*)
(*{"Y2O3 + Fe2O3","Y(NO3)3 + Fe(NO3)3","Y2O3 + Fe3O4","Y(NO3)3 + Fe2O3","Y2O3 + FeO"}],*)
(**)
(*VerificationTest[*)
(*precursorList["Ba2MgGe2O7 <- BaCO3 + MgO + GeO2"],*)
(*{{"BaCO3","MgO","GeO2"}}],*)
(**)
(*VerificationTest[*)
(*precursorList["YFeO3 <- Y2O3 + Fe2O3\n\nYFeO3 <- Y(NO3)3 + Fe(NO3)3\n\nYFeO3 <- Y2O3 + Fe3O4\n\nYFeO3 <- Y(NO3)3 + Fe2O3\n\nYFeO3 <- Y2O3 + FeO"],*)
(*{{"Y2O3","Fe2O3"},{"Y(NO3)3","Fe(NO3)3"},{"Y2O3","Fe3O4"},{"Y(NO3)3","Fe2O3"},{"Y2O3","FeO"}}],*)
(**)
(*VerificationTest[(*check handling of extra blankspaces in reagents *)*)
(*precursorList["Se76Te15Sb9 <- Se + Te + Sb  \n"],*)
(*{{"Se","Te","Sb"}}],*)
(**)
(*VerificationTest[(*check handling of missing target <- prefix *)*)
(*precursorList["MgO + ZnO + BaCO3 + Nb2O5"],*)
(*{{"MgO","ZnO","BaCO3","Nb2O5"}}]}*)
(*]*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(*TestReport[ (*precursor matching*)*)
(*{VerificationTest[*)
(*precursorMatchQ[{{"MgO","GeO2","BaCO3"}},{{"BaCO3","MgO","GeO2"}}]],*)
(**)
(*VerificationTest[*)
(*precursorMatchQ[{{"Y(NO3)3","Fe(NO3)3"}},*)
(*precursorList["YFeO3 <- Y2O3 + Fe2O3\n\nYFeO3 <- Y(NO3)3 + Fe(NO3)3\n\nYFeO3 <- Y2O3 + Fe3O4\n\nYFeO3 <- Y(NO3)3 + Fe2O3\n\nYFeO3 <- Y2O3 + FeO"]]]}*)
(*]*)
